### ISSUE TITLE
Could not find implicit value for parameter sg

### ISSUE THREAD

**Issue by eugenemiretsky** [outworkers/phantom#774] opened 2017-11-17 04:55 UTC
Hello, 
I'm getting the following error when trying to call the store() method. 
`Could not find implicit value for parameter sg: com.outworkers.phantom.macros.SingleGeneric.Aux`. 

We are using scala 2.11.8

**Comment by alexflav23** [comment] 2017-11-17 14:49
@eugenemiretsky Without a schema in place, it's really hard to know what is wrong with this particular macro/implicit gone missing unfortunately. Any chance you could provide that?

**Comment by alexflav23** [comment] 2017-11-25 12:10
@eugenemiretsky Just following up here, we are eager to help and fix all bugs, but please let me know if you could share a schema. If there's any sensitive information, I recommend that you replace any names or field names with random things, all we are interested in is the types and nesting structure of case classes if any.

**Comment by alexflav23** [comment] 2018-01-22 09:31
Hi @eugenemiretsky We've found the problem here presumably, and it's compiler type ambiguity at various phases of the typechecker. The `SingleGeneric.Aux` part uses macros, and the problem is when you need to summon it inside a `CassandraTable`, for some reason the input type to `SingleGeneric`, which is the result of  `TableHelper.Aux`, is not known. Somehow there's a "blank", buggy type, being passed as an argument.


It's only when you do:

```scala
import com.outworkers.phantom.dsl._

case class Entry(
  id: UUID,
  name: String,
  timestamp: DateTime
)

abstract class MyTable extends Table[MyTable, Entry] {
  object id extends UUIDColumn with PartitionKey
  object name extends StringColumn
  object timestamp extends DateTimeColumn
 
  def insertRecord(value: Entry): Future[ResultSet] = {
    store(value).consistencyLevel_=(ConsistencyLevel.All).future()
  }
}
```

The `store` method above is what will fail, as that requires an instance of `SingleGeneric`. However, the same thing done from outside the table, works without issues. The only difference is we are calling the `store` method from different places.

```scala
class MyService extends DatabaseProvider[MyDb] {
  def insertRecord(value: Entry): Future[ResultSet] = {
     db.myTable.store(value).consistencyLevel_=(ConsistencyLevel.All).future()
  }
}
```

We are still working to figure out how this is possible and why `TableHelper` fails to output a proper type or what else goes on, but in the interim the fix for the problem is above, basically define your store methods one level above.

**Comment by setyven** [comment] 2018-02-07 04:36
Hi @alexflav23 , sadly the quick fix doesn't work for me either. They aren't exactly one level above, but I believe that shouldn't be an issue?

**Comment by ShardPhoenix** [comment] 2018-03-13 04:32
Commenting to report that I also had this problem and that the proposed workaround worked for me.

**Comment by alexflav23** [comment] 2018-03-22 17:30
Hi @setyven Do you have a an example schema for us to look at ?

**Comment by MartinEngen** [comment] 2018-04-09 13:49
@alexflav23 Would it be possible to get an example for how to store values in the 'phantom-activator-template' project?
I'm not quite able to get your  recommend method to work, as the class `MyService` would have to be Abstract, and I'm not sure how to call it from within the `MyTable`.

**Comment by alexflav23** [comment] 2018-04-09 15:29
Hi @MartinEngen, that's correct, my example might be incomplete. You need a db connector to make that picture complete, so then the service wouldn't need to be abstract. We'll add examples shortly to the main docs.

**Comment by alexflav23** [comment] 2018-04-10 12:27
Hi @MartinEngen, what version of phantom are you on?

**Comment by MartinEngen** [comment] 2018-04-10 12:32
I'm using the most recent one. 2.24.0

**Comment by alexflav23** [comment] 2018-04-10 14:00
@MartinEngen It's compiling without issues for me: https://github.com/outworkers/phantom/pull/825/files

What version of Scala are you using?

**Comment by MartinEngen** [comment] 2018-04-10 14:32
Ah, it actually works here as well (using Scala 2.12.4). Nice!
I though this structure was not quite ideal, as it inset as clean as the one used in the template in the long run https://github.com/outworkers/phantom-activator-template

A little follow up question on your example. How would you recommend to structure these Store's within the `CassandraDatabase` when you have 20-30++ different tabels and models? 

For now I can just use functions as follows, but it might grow quite a lot. 
```
class CassandraDatabase(override val connector: CassandraConnection) extends Database[CassandraDatabase](connector) {
  object beers extends Beers with Connector

  def storeBeer(beer: Beer): Future[ResultSet] = {
    beers.storeRecord(Beer("a", "b", "c"))
  }
}
```

Thank you very much for that example

**Comment by ShawnBuckley** [comment] 2018-04-19 18:01
Something also worth noting is that this can be triggered if you pass the wrong parameter type to store. Example below:
```
class MyDatabase(connector: connectors.CassandraConnection) extends Database[MyDatabase](connector) {

  object a_table extends ATable with Connector
  object b_table extends BTable with Connector

  def put: Future[Done] = {
    Future.sequence(Seq(
      a_table.store(B()),
      b_table.store(A())
    )).map(_ => Done)
  }
}
```

**Comment by howarth** [comment] 2018-05-10 21:01
I get the error with the following code:

`package db.phantom

import db._

import scala.concurrent.Future
import java.util.UUID

import com.outworkers.phantom.connectors.CassandraConnection
import com.outworkers.phantom.database.{Database, DatabaseProvider}
import com.outworkers.phantom.dsl._

case class PipelineVersionRecord(pipelineId : UUID,
                                 pipelineVersion : UUID,
                                 user : UUID,
                                 tag : Option[String],
                                 pipeline : Array[Byte])

abstract class PipelineVersionTable extends Table[PipelineVersionTable, PipelineVersionRecord] {
  object pipelineId extends UUIDColumn with PartitionKey
  object pipelineVersion extends UUIDColumn with ClusteringOrder with Descending
  object user extends UUIDColumn
  object tag extends OptionalStringColumn
  object pipeline extends BlobColumn

  def findByPipelineId(pipelineId : UUID) : Future[List[PipelineVersionRecord]] =
    select.where(_.pipelineId eqs pipelineId).fetch()

  def findLatestByPipelineId(pipelineId : UUID) : Future[Option[PipelineVersionRecord]] =
    select.where(_.pipelineId eqs pipelineId).one()
}


class PipelineDatabase(override val connector : CassandraConnection) extends Database[PipelineDatabase](connector){
  object pipelineVersions extends PipelineVersionTable with Connector
}

trait PipelineDatabaseProvider extends DatabaseProvider[PipelineDatabase]

trait PipelineService extends PipelineDatabaseProvider{


  def storePipelineVersion(pipelineVersion : PipelineVersionRecord) : Future[WriteResponse] =
    db.pipelineVersions.store(pipelineVersion).ifNotExists.future map {
      _.wasApplied() match {
        case true => WriteSuccess
        case false => WriteFail(WriteFailDuplicate)
      }
    } recover {
      case e : Exception => WriteFail(WriteFailOther(e.getMessage))
    }


  def getPipelineVersionsByPipelineId(pipelineId : UUID) : Future[ReadResponse[List[PipelineVersionRecord]]] =
    db.pipelineVersions.findByPipelineId(pipelineId) map {
      ReadSuccess(_)
    } recover {
      case e : Exception => ReadFail(e.getMessage)
    }

  def getLatestPipelineByPipelineId(pipelineId : UUID) : Future[ReadResponse[Option[PipelineVersionRecord]]] =
    db.pipelineVersions.findLatestByPipelineId(pipelineId) map {
      ReadSuccess(_)
    } recover {
      case e : Exception => ReadFail(e.getMessage)
    }
}`

Error message:

`[error] /Users/dhowarth/cmlh/cmlhgp-server/src/main/scala/db/phantom/FooService.scala:43:30: could not find implicit value for parameter sg: com.outworkers.phantom.macros.SingleGeneric.Aux[db.phantom.PipelineVersionRecord,Repr,HL,Out]
[error]     db.pipelineVersions.store(pipelineVersion).ifNotExists.future map {`

**Comment by howarth** [comment] 2018-05-10 21:08
Oh, my error goes away when I change the 'pipeline' value in the case class to String, and the corresponding to StringColumn.

What type am I supposed to use for a BlobColumn? I tried Vector[Byte] and akka.util.ByteString

**Comment by alexflav23** [comment] 2018-05-10 21:09
@howarth just jump to source and you would see it. `java.nio.ByteBfuffer`.

**Comment by howarth** [comment] 2018-05-10 21:10
Thank you!

**Comment by alexflav23** [comment] 2018-07-31 09:31
Hi @Tr1p0d You are right, we just bit the wrong end of macro API limitations. A fix is being backed in this week, it's unfortunately far more complex than it has to be, for the wrong reasons, which is macro API inconsistencies and random weird behaviour.

The types of columns and other things inside a table are lazily evaluated by the compiler, so depending on which point in the macro logic you refer to them, they unreliably stop working, and it's been a problem for a while.

**Comment by RyanSattler** [comment] 2018-09-13 00:44
Did this change end up being released? Last time I checked I still had this issue.

**Comment by alexflav23** [comment] 2018-09-18 14:13
Hi @RyanSattler, we have a workaround for this now still being trialled, it was not yet released unfortunately, we are going to try and make it happen within the next two weeks.

**Comment by TakiuGit** [comment] 2019-01-04 14:58
Any update on this ? I'm actually following the documentation : https://github.com/outworkers/phantom/blob/develop/docs/basics/database.md
And encounter a similar issue with the version "2.31.0" : 
```
  def store(user: User): Future[ResultSet] = {
    for {
      byId <- db.users.store(user).future()
      byEmail <- db.usersByEmail.store(user).future()
    } yield byEmail
  }
```
Did I missed something ?

**Comment by alexflav23** [comment] 2019-01-04 15:00
Hi @TakiuGit Your schema is probably wrong here. Turn on debugging as per docs to see what's going wrong. Have a look [here](https://github.com/outworkers/phantom/blob/develop/docs/basics/debugging.md#comoutworkersphantommacrosdebugoptionsshowall-flag). You would need to import this where the table is defined, or where this method that doesn't work is defined.

**Comment by TakiuGit** [comment] 2019-01-07 09:33
Hi @alexflav23, thanks for your quick answer, after more investigation, everything work well. The problem was due to my IDE (Intellij) how mark the implicits as absent. Therefore sbt is able to find them during the compilation. I think Intellij has still some problem with scala macro & sbt.

**Comment by alexflav23** [comment] 2019-11-10 17:16
Looks like this ticket can be easily closed as it's been quite a while and as far as I can tell all issues have been resolved. Feel free to re-open if there are more problems. The job of single generic is to match the input arguments to store agains the schema, so if anything fails the mis-alignment is generally the root cause.

**Closed by alexflav23** 2019-11-10 17:16 UTC
Labels: bug, macro-bug
