### ISSUE TITLE
Very high cpu usage after running tests

### ISSUE THREAD

**Issue by aludwiko** [outworkers/phantom#579] opened 2016-11-14 18:35 UTC
I'm not sure if this is a `phantom-sbt` or `cassandra-embedded` issue (probably the second one). But I noticed very high cpu usage after the `test` task. How to reproduce:
1. clone this: git@github.com:aludwiko/cassandra-phantom.git
2. run `sbt`
3. from sbt console run `test` (running `sbt test` will not show the problem)
4. After the tests completed, observe cpu usage. 

Embedded cassandra consume a lot of cpu (tests are already finished).
From a simple sampling I can see this:
![image](https://cloud.githubusercontent.com/assets/2954053/20277441/e8f84078-aaa0-11e6-8bc2-648567ea030a.png)
Which is quite similar to this: https://github.com/jsevellec/cassandra-unit/issues/179

If you have a lot of specs in the project you can observer similar behavior (high cpu usage by `SEPWorker.run`) during tests.

**Comment by alexflav23** [comment] 2016-11-14 21:36
Hi @aludwiko,

There is also a way to enable tests using CCM, which may be a lot less pleasant. This issue does indeed appear to be related to `cassandra-unit`, phantom-sbt just wraps `EmbeddedCassandra` to make sure the correct lifecycle is respected, but it doesn't really do much else.

Apologies, I realise this isn't tremendously helpful. In my own corner of the world I generally run local tests against local Cassandra, and use CCM/Travis Cassandra in CI.

Regards,
Flavian

**Comment by alexflav23** [comment] 2016-11-15 19:10
Hi @aludwiko CCM testing works better in CI where you manually trigger the CCM config. Nothing more automated than that just yet, but we are considering bringing that under the sbt-plugin, instead of Embedded Cassandra.

**Comment by alexflav23** [comment] 2016-12-01 11:00
Hi @aludwiko,

Have a look here:

```python
install:
  - pip install 'requests[security]'
  - pip install ccm
  - ccm create test -v 2.2.8 -n 3 -s
```

**Comment by yleun** [comment] 2017-05-27 05:39
I also noticed this. Implementing a simple get on a single table while load testing 5 request per a second over a duration of 500 s lead to about 1300 new cluster threads created. Even after completion of the test the play application running phantom to Cassandra, threads were held and not released. Repeated load testing lead to more active threads until out-of-memory exceptions are thrown. Hardcoding the result set in place of an actual database call did NOT reproduce open threads - looks like a resource leak on call to database. I used all the default settings on the PoolingOptions. Changes in pooling options of the connection time out or max request per a connection did not make a difference. I tried altering the AKKA thread settings as well with no avail. You can use VisualVM to monitor active threads. Also running netstat indicated a lot of open TCP/IP connections. 

Switching to another DB Client i.e. Quill which also uses Datastax drivers solved the thread leak problem. Quill also uses Datastax which makes me think that Phantom is not properly closing connections to DB.

**Comment by alexflav23** [comment] 2017-05-28 18:50
Hi @yleun,

We won't dismiss this right off the bat especially since there are two people using this already, but I will say I would be extremely surprised if that was the case. Phantom goes through great lengths to encapsulate things like session creation and so on, which aside from a misusage of the DSL should strongly prevent things like that from happening.

The only thing that could make this happen is not a thread leak or a resource leak, but multiple sessions being created in your application for whatever reason. I will pick this up as a high priority item to double check whether or not this is the case, but in the interim it would be worthwhile for you to share some code, particularly around how you acquire those database references and how you are creating the CassandraConnector, because I can definitely see this happening if such an instance is created per actor or something like that, in that case phantom cannot do much but keep spawning sessions and inherently threads that go with it.

Regards.

**Comment by yleun** [comment] 2017-05-29 13:09
Hi Flavian,

Thanks for your prompt response. I really liked Phantom but because I have a hard deadline coming up, we had to move to Quill.
I was in the process of building out a simple sample project that does a simple get and a post with the CassandraConnector over the weekend.
Basically following the example SimpleRecipes, outlined in the project.

I will post a sample project tonite on github (after work). I used gatling to run my load testing. The thread issue can be seen by running VisualVM against the app.
The steps are repeatable in the project with gatling and Cassandra as separate installs.

I really hope that by bringing this issue up we can resolve this problem with Phantom and make it better for anyone to use in the future. ☺ !

I am using:

Cassandra: 3.7 and 3.10
Phantom 2.6.4
(     "com.outworkers"   %% "phantom-connectors"            % phantomVersion,
      "com.outworkers"   %% "phantom-dsl"                   % phantomVersion,
      "com.outworkers"   %% "phantom-thrift"                % phantomVersion,
)
Scala: 2.11.8


Cheers,
YP

**Comment by alexflav23** [comment] 2017-05-29 13:24
Hi @yleun,

Thank you for that, it's a disappointing reply for us of course, given quill is a vastly inferior tool in so many ways, but it sounds like there is a problem to fix and if indeed there is such a big one internally, we'll be more than happy to release a fix overnight.

I keep wondering if this is to the very basic nature of:

```scala
  private[this] lazy val taskExecutor = Executors.newCachedThreadPool()

  implicit lazy val scalaExecutor: ExecutionContextExecutor = ExecutionContext.fromExecutor(taskExecutor)
```

This is what phantom would give you by default, but I imagine under Gatling, this would cause unbounded growth in the cached threadpool and not allow for any efficient re-use. It's why we resort to very different execution context semantics under stress testing and benchmarks, and I can see how that can very easily cause false positives.

Nonetheless, having your example benchmarks will be tremendously helpful, as it may mean we have to swap out that context. I would seriously doubt this is to do with locking or leaking over `Database`, though I don't neglect the possibility, on the grounds that it uses Scala singletons with eval-once semantics to acquire references to things like `session`, but we are here waiting for feedback, as I said this will be fixed today if you can help out with the test cases.

Regards.

**Comment by yleun** [comment] 2017-05-29 14:24
Hi Alex,

I can totally help with testing if outworkers can provide a fix.

Cheers,
YP

**Comment by yleun** [comment] 2017-05-30 00:27
Sample project is here:

https://github.com/yleun/cassandra-loadtest

See README for details.

**Comment by yleun** [comment] 2017-05-30 02:47
The latest commit has a side by side comparison of performance between Quill and Phantom. At about 40 request phantom requests dies because my cpu has run out of threads. 

https://github.com/yleun/cassandra-loadtest/blob/master/loadtest/phantom/results/groupbygroupid-1496110540024/index.html

https://github.com/yleun/cassandra-loadtest/blob/master/loadtest/quill/results/groupbygroupid-1496110270449/index.html

I am getting about about an 80% failure rate which rise the more more request I submit because of lack of connections. Gatling is only trying 3 times. I think because the posts are faster than the gets they get more connections which is why you get an unbalance between GET and POST request. When phantom does succeed in posting the POSTs appear very fast. Phantom is returning the following errors:

j.n.ConnectException: Failed to open a socket.	254	76.737 %
j.u.c.TimeoutException: Request timeout to localhost/127.0.0.1:9000 after 60000 ms	76	22.961 %
status.find.is(200), but actually found 500	1	0.302 %

**Comment by alexflav23** [comment] 2017-06-16 11:33
Hi @aludwiko,

After a lot of further investigation, including running the above loadtest in depth, this issue is related to Embedded Cassandra rather than to phantom. We are working on completely replacing that part of the testkit with a for more advanced alternative that no longer uses embedded Cassandra, and instead relies on other tools to achieve the same purpose and much more.

With regards to the loadtest that @yleun created, I've look at the implementation in depth, and the failure rates indicated are actually because the load test is executing invalid queries in Cassandra, as far as I was able to tell. Neither Quill nor Phantom type-check that part of the where clause yet, and we have added a ticket to resolve that as soon as possible, as basically we do not catch on to the fact that only part of the partition key was specified, which results in invalid Cassandra queries.

You can check the updated results here at [outworkers/cassandra-loadtest](https://github.com/outworkers/cassandra-loadtest), where both `phantom` and `quill` are executing the same queries against the same schema, and it's obvious they both have exactly the same 100% response success rate when executing queries.

I'm going to close this ticket and feel free to chase this with the implementor of embedded-cassandra, as far as we are concerned the current implementation of `phantom-sbt` is no longer supported or maintained and we are actively working to replace it completely. The new version will not be available open source, but it will be able to do things like:

- Allow you to test against whatever version of Cassandra you want, specified directly via conf.
- Allow you to test against an entire ring, as opposed to a single node.
- Allow you to traverse an entire project and automatically create schema files out of it.
- Allow you to auto-generate an entire database module from a database schema.
- Allow direct compatibility with phantom-migrations, which is a way to perform automated schema and data migrations with phantom, this feature is however not available open source.

**Closed by alexflav23** 2017-06-16 11:33 UTC

**Comment by yleun** [comment] 2017-06-19 17:11
Hi Alex,

Thanks for working into this. I can test it tonite.
FYI all my load testing was done on one of a localhost 3.10 version of Cassandra and AMI EC2 instance on Amazon in a Docker container with Cassandra 3.7.

I did NOT do any load testing on the embedded Cassandra instances.


Thx,
YP

**Comment by yleun** [comment] 2017-06-20 01:13
Hi Alex,


I am running against my local host:


OS X El Capitan, Version 10.11.1, MacBook Pro, Processor 2 GHz, Memory 8 GB



with the following software version:


apache-cassandra 3.10

phantom 2.9.2

scala 2.11.8

sbt 0.13.13


I am NOT running the embedded cassandra. I don't think the problem is fixed. Below I enumerate many repeatable and observable ways for anyone to recreate the errors I am experiencing. I have done all that I can to show that Phantom has a memory leak and is not closing it's DB or TCP/IP connections. If this does not interest you than that's the end of that.



Steps to Reproduce:


I ran "sbt run" on the latest version of phantom: 2.9.2 with Gatling on github project:


https://github.com/yleun/cassandra-loadtest


and I am still running into the same issues. Connections are not being released even after load test completes. Load test runs and at about 40 requests the connections are used up and not released and I start getting connect exceptions:


j.n.ConnectException: Failed to open a socket.                     53 (96.36%)




Before my load test, call to api succeeds. 15 mins after the load test, call to API fails with the following exception:


{"code":"ServiceError","errors":["Service is unavailable. Group information cannot be retrieved. RepositoryFailure(java.lang.IllegalStateException: failed to create a child event loop)"]}



To monitor memory I did a simple ps test on my localhost mac machine I ran ps -aux | grep java:



  1.  After SBT run, before load test:


USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND

yuenpingleung     9469   1.4  6.3  5029948 528956 s000  S+    8:37pm   0:24.13 /usr/bin/java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -jar /Users/yuenpingleung/yp/projects/software/sbt/bin/sbt-launch.jar run


2. After SBT run, ran 1 post call to update cassandra DB:


USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND

yuenpingleung     9469   5.7  9.0  5248372 758772 s000  S+    8:37pm   0:49.07 /usr/bin/java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -jar /Users/yuenpingleung/yp/projects/software/sbt/bin/sbt-launch.jar run



3. During load test 35s in - steady rise in memory:


USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND

yuenpingleung     9469   5.7  9.0  5248372 758772 s000  S+    8:37pm   0:49.07 /usr/bin/java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -jar /Users/yuenpingleung/yp/projects/software/sbt/bin/sbt-launch.jar run


4. After load test:


USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND

yuenpingleung     9469   2.4  9.5  6138036 795592 s000  R+    8:37pm   1:28.11 /usr/bin/java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -jar /Users/yuenpingleung/yp/projects/software/sbt/bin/sbt-launch.jar run

5. 5 mins after load test, notice memory not released:


USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND

yuenpingleung     9469   7.6  9.5  6138036 797988 s000  S+    8:37pm   2:05.38 /usr/bin/java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -jar /Users/yuenpingleung/yp/projects/software/sbt/bin/sbt-launch.jar run


6. 15 mins after load test, notice memory not released:


USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND

yuenpingleung     9469   3.6  9.6  6137432 802008 s000  S+    8:37pm   3:35.07 /usr/bin/java -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxMetaspaceSize=256m -jar /Users/yuenpingleung/yp/projects/software/sbt/bin/sbt-launch.jar run




________


Play Exception:


play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IllegalStateException: failed to create a child event loop]]

at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)

at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)

at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)

at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)

at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)

at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)

at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)

at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)

at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)

at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)

Caused by: java.lang.IllegalStateException: failed to create a child event loop

at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68)

at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)

at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:70)

at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:65)

at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:56)

at com.datastax.driver.core.NettyUtil.newEventLoopGroupInstance(NettyUtil.java:139)

at com.datastax.driver.core.NettyOptions.eventLoopGroup(NettyOptions.java:99)

at com.datastax.driver.core.Connection$Factory.<init>(Connection.java:774)

at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1446)

at com.datastax.driver.core.Cluster.init(Cluster.java:159)

Caused by: io.netty.channel.ChannelException: failed to open a new selector

at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:157)

at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:148)

at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:102)

at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)

at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)

at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:70)

at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:65)

at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:56)

at com.datastax.driver.core.NettyUtil.newEventLoopGroupInstance(NettyUtil.java:139)

at com.datastax.driver.core.NettyOptions.eventLoopGroup(NettyOptions.java:99)

Caused by: java.io.IOException: Too many open files in system

at sun.nio.ch.IOUtil.makePipe(Native Method)

at sun.nio.ch.KQueueSelectorImpl.<init>(KQueueSelectorImpl.java:84)

at sun.nio.ch.KQueueSelectorProvider.openSelector(KQueueSelectorProvider.java:42)

at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:155)

at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:148)

at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:102)

at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)

at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)

at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:70)

at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:65)










________________________________
From: Yuen-Ping Leung
Sent: Monday, June 19, 2017 1:11 PM
To: outworkers/phantom; outworkers/phantom
Cc: Mention
Subject: RE: [outworkers/phantom] Very high cpu usage after running tests (#579)


Hi Alex,



Thanks for working into this. I can test it tonite.

FYI all my load testing was done on one of a localhost 3.10 version of Cassandra and AMI EC2 instance on Amazon in a Docker container with Cassandra 3.7.



I did NOT do any load testing on the embedded Cassandra instances.





Thx,
YP

**Comment by yleun** [comment] 2017-06-20 02:15
[outworkers/phantom] Very high cpu usage after running tests (#579)

[Draft]
This message hasn't been sent.Saved on: Mon 6/19/2017 10:07 PM
Also I changed my load test to only do POST that is only inserts without any finds as not to create this invalid query error and still I ran into the same problems.

I get the connection error, can post before load test but cannot post after load test and memory is not released.

thx,
YP


________________________________

**Comment by alexflav23** [comment] 2017-06-20 08:54
@yleun Have you merged my updated code?

**Comment by yleun** [comment] 2017-06-20 13:22
Hi Alex,

Also I changed my load test to only do POST that is only inserts without any finds (selects) as not to create this invalid query error and still I ran into the same problems.

I get the following symptoms


-        connection error in load test

-        can post before load test but CANNOT post after load test

-        memory is not released through 'ps aux' command

thx,
YP
